export interface DemoListing {
  _id: string
  address: string
  city: string
  price: number | null
  propertyType: string
  lotSize: string | null
  buildingArea: number | null
  status: string
  mlsNumber: string
  featured: boolean
  slug: string
  mainImage: string
  description: string
  images: string[]
}

export const DEMO_LISTINGS: DemoListing[] = [
  {
    _id: 'demo-1',
    address: '17111 + 17101 80 Ave',
    city: 'Surrey',
    price: 12899000,
    propertyType: 'Development Land',
    lotSize: '5.2',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: true,
    slug: '17111-17101-80-ave',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/17111-17101-80-Ave_development-land-varing-website-560x380.png',
    description: 'Prime Fleetwood development land assembly spanning two legal lots. Situated along the 80 Avenue corridor with proximity to transit, schools, and commercial amenities. Ideal for townhouse or medium-density residential development under current OCP designations.',
    images: ['https://www.varinggroup.com/wp-content/uploads/17111-17101-80-Ave_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-2',
    address: '2301-2337 152 St',
    city: 'Surrey',
    price: 8850000,
    propertyType: 'Development Land',
    lotSize: '1.8',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: true,
    slug: '2301-2337-152-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/2301-2337-152-St_development-land-varing-website-560x380.png',
    description: 'Strategically located assembly in the Semiahmoo Town Centre plan area. High-density mixed-use potential under the evolving OCP. Excellent exposure along 152 Street with strong traffic counts and proximity to established retail corridors.',
    images: ['https://www.varinggroup.com/wp-content/uploads/2301-2337-152-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-3',
    address: '3352 200 St',
    city: 'Langley',
    price: 6200000,
    propertyType: 'Development Land',
    lotSize: '4.6',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '3352-200-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/3352-200-St_development-land-for-sale-560x380.png',
    description: 'Large acreage in the Booth-Brookswood neighbourhood with significant development upside. Situated in a rapidly evolving corridor with new residential communities underway. Suitable for subdivision or cluster housing development.',
    images: ['https://www.varinggroup.com/wp-content/uploads/3352-200-St_development-land-for-sale-560x380.png'],
  },
  {
    _id: 'demo-4',
    address: '9341 177 St',
    city: 'Surrey',
    price: 5950000,
    propertyType: 'Development Land',
    lotSize: '3.1',
    buildingArea: null,
    status: 'Reduced',
    mlsNumber: '',
    featured: false,
    slug: '9341-177-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/9341-177-St_development-land-varing-website-560x380.png',
    description: 'Anniedale-Tynehead acreage with NCP designation supporting future residential development. Located in one of Surrey\'s fastest-growing corridors with substantial infrastructure investment planned. Recently reduced for motivated sale.',
    images: ['https://www.varinggroup.com/wp-content/uploads/9341-177-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-5',
    address: '23638 Dewdney Trunk Rd',
    city: 'Maple Ridge',
    price: 5250000,
    propertyType: 'Development Land',
    lotSize: '6.8',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '23638-dewdney-trunk-rd',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/23638-Dewdney-Trunk-Rd_development-land-varing-website-560x380.png',
    description: 'Cottonwood corridor acreage along Dewdney Trunk Road with frontage and development potential. Located in an area experiencing rapid residential growth with new community infrastructure. Suitable for subdivision or estate-lot development.',
    images: ['https://www.varinggroup.com/wp-content/uploads/23638-Dewdney-Trunk-Rd_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-6',
    address: '18493 Fraser Hwy',
    city: 'Surrey',
    price: 4900000,
    propertyType: 'Development Land',
    lotSize: '2.4',
    buildingArea: null,
    status: 'Reduced',
    mlsNumber: '',
    featured: false,
    slug: '18493-fraser-hwy',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/18493-Fraser-Hwy_development-land-varing-website-560x380.png',
    description: 'Clayton SkyTrain corridor site with exceptional transit-oriented development potential. Located along Fraser Highway in the path of the Surrey-Langley SkyTrain extension. Reduced pricing reflects motivated court-ordered sale timeline.',
    images: ['https://www.varinggroup.com/wp-content/uploads/18493-Fraser-Hwy_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-7',
    address: '26899 + 26963 Old Yale Rd',
    city: 'Langley',
    price: 3950000,
    propertyType: 'Development Land',
    lotSize: '2.9',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '26899-26963-old-yale-rd',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/26899-26963-Old-Yale-Rd_development-land-varing-website-560x380.png',
    description: 'Aldergrove assembly on Old Yale Road with strong development fundamentals. Two-lot consolidation offering increased density potential under current land use policies. Well-serviced location with proximity to the Aldergrove commercial core.',
    images: ['https://www.varinggroup.com/wp-content/uploads/26899-26963-Old-Yale-Rd_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-8',
    address: '13698 113 Ave',
    city: 'Surrey',
    price: 2485000,
    propertyType: 'Development Land',
    lotSize: '0.5',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '13698-113-ave',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/13698-113-Ave_development-land-varing-website-560x380.png',
    description: 'Bolivar Heights infill opportunity with OCP support for increased residential density. Compact lot suited for townhouse or duplex development in an established neighbourhood with strong rental demand and transit access.',
    images: ['https://www.varinggroup.com/wp-content/uploads/13698-113-Ave_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-9',
    address: '10556 + 10566 140 St',
    city: 'Surrey',
    price: 2299000,
    propertyType: 'Development Land',
    lotSize: '0.6',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '10556-10566-140-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/10556-10566-140-St_development-land-varing-website-560x380.png',
    description: 'Guildford area assembly at 140 Street and 104A Avenue. Two-lot consolidation with redevelopment potential under current OCP designations. Located near transit, schools, and the Guildford Town Centre commercial district.',
    images: ['https://www.varinggroup.com/wp-content/uploads/10556-10566-140-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-10',
    address: '36263 North Parallel Rd',
    city: 'Abbotsford',
    price: 5900000,
    propertyType: 'Development Land',
    lotSize: '10.2',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '36263-north-parallel-rd',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/36263-North-Parallel-Rd_development-land-varing-website-560x380.png',
    description: 'Sumas Prairie acreage with significant agricultural and development potential. Large-format site along North Parallel Road in one of Abbotsford\'s most active growth corridors.',
    images: ['https://www.varinggroup.com/wp-content/uploads/36263-North-Parallel-Rd_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-11',
    address: '1156 Fremont-Devon St',
    city: 'Coquitlam',
    price: 2250000,
    propertyType: 'Development Land',
    lotSize: '0.8',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '1156-fremont-devon-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/1156-Fremont-Devon-St_development-land-varing-website-560x380.png',
    description: 'Northeast Coquitlam development site with strong growth fundamentals. Located in an emerging residential corridor with proximity to transit and community amenities.',
    images: ['https://www.varinggroup.com/wp-content/uploads/1156-Fremont-Devon-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-12',
    address: '2317 Gook Rd',
    city: 'Quesnel',
    price: 995000,
    propertyType: 'Development Land',
    lotSize: '40.0',
    buildingArea: null,
    status: 'Active',
    mlsNumber: '',
    featured: false,
    slug: '2317-gook-rd',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/2317-Gook-Rd_development-land-varing-website-560x380.png',
    description: 'Large acreage along the Cariboo Highway corridor in Quesnel. Significant land holding with multiple potential uses including agricultural, rural residential, or resource-based development.',
    images: ['https://www.varinggroup.com/wp-content/uploads/2317-Gook-Rd_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-13',
    address: '3338 200 St',
    city: 'Langley',
    price: null,
    propertyType: 'Development Land',
    lotSize: '4.8',
    buildingArea: null,
    status: 'Firm',
    mlsNumber: '',
    featured: false,
    slug: '3338-200-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/3338-200-St_development-land-varing-website-560x380.png',
    description: 'Booth-Brookswood development site now under contract. Situated in one of Langley\'s most sought-after growth corridors with strong townhouse and single-family demand.',
    images: ['https://www.varinggroup.com/wp-content/uploads/3338-200-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-14',
    address: '4272 176 St',
    city: 'Surrey',
    price: null,
    propertyType: 'Development Land',
    lotSize: '2.1',
    buildingArea: null,
    status: 'Sold',
    mlsNumber: '',
    featured: false,
    slug: '4272-176-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/4272-176-St_development-land-varing-website-560x380.png',
    description: 'South Surrey development land successfully sold through court-ordered mandate. Prime location along the 176 Street corridor.',
    images: ['https://www.varinggroup.com/wp-content/uploads/4272-176-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-15',
    address: '9010 156A St',
    city: 'Surrey',
    price: null,
    propertyType: 'Development Land',
    lotSize: '0.4',
    buildingArea: null,
    status: 'Sold',
    mlsNumber: '',
    featured: false,
    slug: '9010-156a-st',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/9010-156A-St_development-land-varing-website-560x380.png',
    description: 'Fleetwood Tynehead infill site successfully sold. Court-ordered mandate completed with competitive market outcome.',
    images: ['https://www.varinggroup.com/wp-content/uploads/9010-156A-St_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-16',
    address: '15738 North Bluff Rd',
    city: 'White Rock',
    price: null,
    propertyType: 'Development Land',
    lotSize: '0.3',
    buildingArea: null,
    status: 'Sold',
    mlsNumber: '',
    featured: false,
    slug: '15738-north-bluff-rd',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/15738-North-Bluff-Rd_development-land-varing-website-560x380.png',
    description: 'North Bluff corridor site in White Rock, successfully sold through court-ordered mandate. High-density potential in premium White Rock location.',
    images: ['https://www.varinggroup.com/wp-content/uploads/15738-North-Bluff-Rd_development-land-varing-website-560x380.png'],
  },
  {
    _id: 'demo-17',
    address: '14318 60 Ave',
    city: 'Surrey',
    price: null,
    propertyType: 'Development Land',
    lotSize: '1.2',
    buildingArea: null,
    status: 'Sold',
    mlsNumber: '',
    featured: false,
    slug: '14318-60-ave',
    mainImage: 'https://www.varinggroup.com/wp-content/uploads/14318-60-Ave_development-land-varing-website-560x380.png',
    description: 'South Newton development site successfully sold. Court-ordered mandate completed in established Surrey neighbourhood with strong residential demand.',
    images: ['https://www.varinggroup.com/wp-content/uploads/14318-60-Ave_development-land-varing-website-560x380.png'],
  },
]
